---
- name: Ensure VPC {{ aws_vpc_name }} is present
  ec2_vpc_net:
    name: "{{ aws_vpc_name }}"
    cidr_block: "{{ aws_vpc_cidr_block }}"
    dns_hostnames: "{{ aws_vpc_dns_hostnames }}"
    dns_support: "{{ aws_vpc_dns_support }}"
    purge_cidrs: yes
    region: "{{ aws_region }}"
    tags:
      Environment: "{{ aws_environment }}"
    state: present

# - name: Ensure VPC Internet Gateway is present
#   ec2_vpc_igw:
#
# - name: Ensure VPC Nat Gateway is present
#   ec2_vpc_nat_gateway:
#
# - name: Ensure VPC Route Tables are configured correctly
#   ec2_vpc_route_table:
#
# - name: Create AWS ELB
#   elb_application_lb:
#
# - name: Ensure Target groups are present
#   elb_target_group:
